
SELECT      ID, TODO ,  replace(TODO,'*','')
FROM          aux_codANT
WHERE ID/3.00 - round(ID/3.00,2) = 0


SELECT   ID,(ID+2)  , convert(int, replace(TODO,'*','')  )
FROM          aux_codANT
WHERE (ID-1)/3.00 - round((ID-1)/3.00,2) = 0

SELECT   (ID/3.00)-0.01,floor( (ID/3.00)-0.01)   ,*
FROM          aux_codANT A


-------------------------------
SELECT   *
update A set IDMAX = IDposta
FROM          aux_codANT A
inner join (
		SELECT   ID IDini , (ID+2) IDfin  , convert(int, replace(TODO,'*','')  ) IDposta
		FROM          aux_codANT
		WHERE (ID-1)/3.00 - round((ID-1)/3.00,2) = 0
		) VV
on A.ID between IDini and IDfin

-------------------------------
SELECT  *
FROM          aux_codANT A 


--UPDATE a set omitir = 'False'
--FROM          aux_codANT a
--WHERE omitir  is null


declare @e varchar(100) =  '''' + '.'

SELECT R1.IDMAX , 
SUBSTRING(  rtrim(LTRIM(replace(R2.TODO ,      '02  FILLER  PIC X(78)   VALUE','') )) ,2,100)            +
rtrim(LTRIM(substring(   replace(R3.TODO,@e ,'' ),36,100) ))  ANTIGUEDADES
into #FWW
		FROM 		
				(SELECT IDMAX , TODO FROM (
				SELECT  *, ROW_NUMBER() OVER(PARTITION BY IDMAX ORDER BY ID) AS RowNumber
				FROM          aux_codANT A 
				WHERE Omitir = 0
				) X1
		WHERE RowNumber = 1 )  R1
		inner join 
				(SELECT  IDMAX , TODO  FROM (
				SELECT  *, ROW_NUMBER() OVER(PARTITION BY IDMAX ORDER BY ID) AS RowNumber
				FROM          aux_codANT A
				WHERE Omitir = 0
				) X2
		WHERE RowNumber = 2  ) R2
		on R1.IDMAX = R2.IDMAX
		inner join 
				(SELECT  IDMAX , TODO  FROM (
				SELECT  *, ROW_NUMBER() OVER(PARTITION BY IDMAX ORDER BY ID) AS RowNumber
				FROM          aux_codANT A
				WHERE Omitir = 0
				) X3
		WHERE RowNumber = 3  ) R3
		on R2.IDMAX = R3.IDMAX






SELECT IDMAX , ANTIGUEDADES,
SUBSTRING(ANTIGUEDADES,1,3) A,
SUBSTRING(ANTIGUEDADES,4,3) B,
SUBSTRING(ANTIGUEDADES,7,3) C,
SUBSTRING(ANTIGUEDADES,10,3) D,
SUBSTRING(ANTIGUEDADES,13,3) E,
SUBSTRING(ANTIGUEDADES,16,3) F,
SUBSTRING(ANTIGUEDADES,19,3) G,
SUBSTRING(ANTIGUEDADES,22,3) H,
SUBSTRING(ANTIGUEDADES,25,3) I,
SUBSTRING(ANTIGUEDADES,28,3) J,
SUBSTRING(ANTIGUEDADES,31,3) K,
SUBSTRING(ANTIGUEDADES,34,3) L,
SUBSTRING(ANTIGUEDADES,37,3) M,
SUBSTRING(ANTIGUEDADES,40,3) N,
SUBSTRING(ANTIGUEDADES,43,3) O,
SUBSTRING(ANTIGUEDADES,46,3) P,
SUBSTRING(ANTIGUEDADES,49,3) Q,
SUBSTRING(ANTIGUEDADES,52,3) R,
SUBSTRING(ANTIGUEDADES,55,3) S,
SUBSTRING(ANTIGUEDADES,58,3) T,
SUBSTRING(ANTIGUEDADES,61,3) U,
SUBSTRING(ANTIGUEDADES,64,3) V
FROM #FW


SELECT IDMAX as IdMunicipio,
-- ANTIGUEDADES,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,1,3)) A,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,4,3)) B,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,7,3)) C,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,10,3)) D,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,13,3)) E,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,16,3)) F,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,19,3)) G,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,22,3)) H,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,25,3)) I,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,28,3)) J,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,31,3)) K,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,34,3)) L,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,37,3)) M,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,40,3)) N,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,43,3)) O,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,46,3)) P,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,49,3)) Q,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,52,3)) R,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,55,3)) S,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,58,3)) T,
CONVERT(INT,SUBSTRING(ANTIGUEDADES,61,3)) U,
CASE WHEN CONVERT(INT,SUBSTRING(ANTIGUEDADES,64,3)) = 0 
	 THEN NULL 
	 ELSE CONVERT(INT,SUBSTRING(ANTIGUEDADES,64,3)) 
	 END V
into Antiguedades_Municipios_2Sem
FROM #FWW

